config/routes.rb
Rails.application.routes.draw do
  # adminとcustomerのdeviseを作成,アクションがかぶるので下記設定で整えた
  devise_for :admin, :skip => [:registrations, :password],
                      controllers: {sessions: 'admin/sessions'}
  
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  
  # namespaceを使用、pubilcのURLにはpublicを表示したくないので、scope modul:で実装
  scope modul: :public do
    root to: "public/homes#top"
    get "/about" => "public/homes#about"
    get "/customers/my_page" => "public/customers#show", as: "my_page"
    # get "/items" => "public/items#index"
    resources :items, only: [ :index,:show ], module: :public
    resources :addresses, only: [ :index, :create, :edit, :update, :destroy ], module: :public
    
    resources :customers, only: [ :edit, :update ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        get "unsubscribe"
        patch "withdraw"
      end 
    end 
    
    resources :orders, only: [ :new, :create, :index, :show ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        post "confirm"
        get "complete"
      end 
    end 
    
    resources :cart_items, only: [ :index, :update, :create, :destroy ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        delete "destroy_all"
      end 
    end 
  end 
  
  # namespaceを使用、adminのURLにはadminを表示するので、namespaceで実装
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [ :index, :new, :create, :show, :edit, :update ]
    resources :customers, only: [ :index, :show, :edit, :update ]
    resources :orders, only: [ :show, :update ]
    resources :genres, only: [ :index, :create, :edit, :update ]
    resources :order_details, only: [:update]
  end 
end

app/models/item.rb
class Item < ApplicationRecord
  has_many:cart_items, dependent: :destroy
  has_many:order_details, dependent: :destroy
  belongs_to:genre
  
  # refileやattachment imgを使用するために必要
  attachment :image
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page])
  end 
  
  def new 
    @item = Item.new
  end 
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end 
  
  def show
    @item = Item.find(params[:id])
  end 
  
  def edit
    @item = Item.find(params[:id])
  end 
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end 
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id,:name,:image,:introduction,
                                 :price,:is_active)
  end 
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 bg-light text-center my-4">
      <h5>商品編集</h5>
    </div>
  </div>
  
  <!--new画面とほぼ同じ-->
  <%= form_with model: [:admin,@item], local:true do |f| %>
  <div class="row">
    <table class="table table-borderless" style="table-layout:fixed;">
      <tbody>
        <tr><th style="width:200px;">商品画像</th><td><%= f.attachment_field :image %></td></tr>
        <tr><th>商品名</th><td><%= f.text_field :name, placeholder: "商品名", size: "30" %></td></tr>
        <tr><th>商品説明</th><td><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "30x8" %></td></tr>
        <!--f.collection_select プロパティ名, オブジェクトの配列, value属性の項目, テキストの項目 -->
        <tr><th>ジャンル</th><td><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--" %></td></tr>
        <tr><th>税抜価格</th><td><%= f.text_field :price, placeholder: "1000" %>円</td></tr>
        <tr>
          <th>販売ステータス</th>
          <!--is_active初期値trueであれば販売中、退会の場合falseになるので販売停止中-->
          <td>
              <%= f.radio_button :is_active, "true" %>
              <%= f.label :is_active, "販売中", value: "true" %>
              <%= f.radio_button :is_active, "false" %>
              <%= f.label :is_active, "販売停止中", value: "false" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  
  <div class="text-center">
    <%= f.submit "変更を保存", class: "btn btn-success px-4" %>
  </div>
  <% end %>
  
  
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 bg-light text-center my-4">
      <h5>商品一覧</h5>
    </div>
  
    
    <!--font-awesome　＋マークの新規作成リンク-->
    <div class="col-md-1 offset-md-9 pull-right d-flex align-items-center">
      <%= link_to new_admin_item_path,style: "color:gray" do %>
        <i class="fas fa-plus-circle fa-2x"></i>
      <% end %>
    </div>
  </div>
  
  <!--テーブルメソッドを使用して一覧の繰り返し表示-->
  <div class="row">
    <table class="table">
      <thead class="bg-light">
        <tr>
          <th class="border-dark">商品ID</th><th class="border-dark">商品名</th>
          <th class="border-dark">税抜価格</th><th class="border-dark">ジャンル</th><th class="border-dark">ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td class="border-bottom border-dark"><%= item.id %></td>
            <td class="border-bottom border-dark"><%= link_to item.name, admin_item_path(item.id), class: "text-dark border-bottom border-dark"%></td>
            <td class="border-bottom border-dark"><%= item.price %></td>
            <td class="border-bottom border-dark"><%= item.genre.name %></td>
            <td class="border-bottom border-dark">
              <% if item.is_active == true %>
                <div class="text-success">販売中</div>
              <% else %>
                <div class="text-secondary">販売停止中</div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <!--ページネイト-->
  <div class="row">
    <div class="mx-auto">
      <%= paginate @items %>
    </div>
  </div>
  
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 bg-light text-center my-4">
      <h5>商品新規登録</h5>
    </div>
  </div>
  
  <%= form_with model: [:admin,@item], local:true do |f| %>
  <div class="row">
    <table class="table table-borderless" style="table-layout:fixed;">
      <tbody>
        <tr><th style="width:200px;">商品画像</th><td><%= f.attachment_field :image %></td></tr>
        <tr><th>商品名</th><td><%= f.text_field :name, placeholder: "商品名", size: "30" %></td></tr>
        <tr><th>商品説明</th><td><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "30x8" %></td></tr>
        <!--f.collection_select プロパティ名, オブジェクトの配列, value属性の項目, テキストの項目 -->
        <tr><th>ジャンル</th><td><%= f.collection_select :genre_id, Genre.all, :id, :name, prompt: "--選択してください--" %></td></tr>
        <tr><th>税抜価格</th><td><%= f.text_field :price, placeholder: "1000" %>円</td></tr>
        <tr>
          <th>販売ステータス</th>
          <!--is_active初期値trueであれば販売中、退会の場合falseになるので販売停止中-->
          <td>
              <%= f.radio_button :is_active, "true" %>
              <%= f.label :is_active, "販売中", value: "true" %>
              <%= f.radio_button :is_active, "false" %>
              <%= f.label :is_active, "販売停止中", value: "false" %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  
  <div class="row">
    <div class="col-2 offset-3">
      <%= f.submit "新規登録", class: "btn btn-success px-4" %>
    </div>
  </div>
  <% end %>
  
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2 bg-light text-center my-4">
      <h5>商品詳細</h5>
    </div>
  </div>
  
  <div class="row">
    <!--画像の表示領域をcolで分け、attachment_image_tagを使用する-->
    <div class="col-md-3">
      <%= attachment_image_tag @item, :image, :fill, 200, 200, format: 'jpeg', fallback: "no_image.jpg", size: "200x200" %>
    </div>
    
    <!--商品詳細情報を表示するtable-->
    <div class="col-md-9">
      <table class="table table-borderless">
        <tr>
          <th>商品名</th><td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th><td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>ジャンル</th><td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <th>税込価格<br/>(税抜き価格)</th><td><%= @item.price %></td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <% if @item.is_active == true %>
            <td class="text-success">販売中</td>
          <% else %>
            <td class="text-danger">売切れ</td>
          <% end %>
        </tr>
      </table>
    </div>
    
    <div class="mx-auto">
      <%= link_to "編集する", edit_admin_item_path(params[:id]), class: "btn btn-success px-3" %>
    </div>
  </div>
  
</div>