config/routes.rb
Rails.application.routes.draw do
  # adminとcustomerのdeviseを作成,アクションがかぶるので下記設定で整えた
  devise_for :admin, :skip => [:registrations, :password],
                      controllers: {sessions: 'admin/sessions'}
  
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  
  # namespaceを使用、pubilcのURLにはpublicを表示したくないので、scope modul:で実装
  scope modul: :public do
    root to: "public/homes#top"
    get "/about" => "public/homes#about"
    get "/customers/my_page" => "public/customers#show", as: "my_page"
    # get "/items" => "public/items#index"
    resources :items, only: [ :index,:show ], module: :public
    resources :addresses, only: [ :index, :create, :edit, :update, :destroy ], module: :public
    
    resources :customers, only: [ :edit, :update ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        get "unsubscribe"
        patch "withdraw"
      end 
    end 
    
    resources :orders, only: [ :new, :create, :index, :show ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        post "confirm"
        get "complete"
      end 
    end 
    
    resources :cart_items, only: [ :index, :update, :create, :destroy ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        delete "destroy_all"
      end 
    end 
  end 
  
  # namespaceを使用、adminのURLにはadminを表示するので、namespaceで実装
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [ :index, :new, :create, :show, :edit, :update ]
    resources :customers, only: [ :index, :show, :edit, :update ]
    resources :orders, only: [ :show, :update ]
    resources :genres, only: [ :index, :create, :edit, :update ]
    resources :order_details, only: [:update]
  end 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many:cart_items, dependent: :destroy
  has_many:orders, dependent: :destroy
  has_many:addresses, dependent: :destroy
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page])
  end 
  
  def show
    @customer = Customer.find(params[:id])
  end 
  
  def edit
    @customer = Customer.find(params[:id])
  end 
  
  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end 
  
  private
  
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana,
                                    :postal_code, :address, :telephone_number, :email, :is_deleted,)
  end
  
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  
  # customerが新規作成後のリダイレクト先
  def after_sign_up_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Customer)
      my_page_path
    end
  end
  
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  
  # customerがログイン後のリダイレクト先
  def after_sign_in_path_for(resource_or_scope)
    if resource_or_scope.is_a?(Customer)
      root_path
    end
  end
  
  # ログイン時に下記判定するように指示
  before_action :reject_inactive_customer, only: [:create]
  
  # もしcustomerのログインがあれば、アクティブなpasswordと、is_deletedのステータス(退会)によって
  # ログインさせず、エラーを吐く
  def reject_inactive_customer
    @customer = Customer.find_by(email: params[:customer][:email])
    if @customer
      if @customer.valid_password?(params[:customer][:password]) && @customer.is_deleted
        flash[:error] = 'このアカウントは退会済みです。別のメールアドレスをご登録ください。'
        redirect_to new_customer_session_path
      end 
    end 
  end 
  
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-auto bg-light text-center mb-2">
      <h5><%= @customer.first_name + @customer.last_name %>さんの会員情報編集</h5>
    </div>
  </div>
  
  <!--テーブルメソッドを使用して一覧の表示-->
  <div class="row">
    <!--form_withはtableの外に配置する。中に中途半端に置くと二回送信できない-->
    <%= form_with model:[:admin,@customer], local:true do |f| %>
      <table class="table table-borderless pr-5" style="table-layout:fixed;">
        <tbody>
          <tr>
            <th style="width:200px;">会員ID</th>
            <td style="width:40%;"><%= @customer.id %></td>
            <td style="width:40%;"></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= f.text_field :last_name, class: "form-control border-dark" %></td>
            <td><%= f.text_field :first_name, class: "form-control border-dark" %></td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td><%= f.text_field :last_name_kana, class: "form-control border-dark" %></td>
            <td><%= f.text_field :first_name_kana, class: "form-control border-dark" %></td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= f.text_field :postal_code, class: "form-control border-dark" %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= f.text_field :address, class: "form-control border-dark"%></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= f.text_field :telephone_number, class: "form-control border-dark" %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= f.email_field :email, class: "form-control border-dark" %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <!--ラジオボタン　有効でfalse,退会でtrueを返す-->
            <td>
              <%= f.radio_button :is_deleted, "false" %>
              <%= f.label :is_deleted, "有効", value: "false" %>
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, "退会", value: "true" %>
            </td>
          </tr>
          <tr>
            <th></th>
            <td><%= f.submit "変更を保存", class: "btn btn-success px-3" %></td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </div>
  
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-auto bg-light text-center mb-2">
      <h5>会員一覧</h5>
    </div>
  </div>
  
  <!--テーブルメソッドを使用して一覧の繰り返し表示-->
  <div class="row">
    <table class="table">
      <thead class="bg-light">
        <tr>
          <th>会員ID</th><th style="text-decoration: underline">氏名</th><th>メールアドレス</th><th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id), class: "text-dark border-bottom border-dark"%></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted == false %>
                <div class="text-success">有効</div>
              <% else %>
                <div class="text-secondary">無効</div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
  <!--ページネイト-->
  <div class="row">
    <div class="mx-auto">
            <%= paginate @customers %>
    </div>
  </div>
  
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-auto bg-light text-center mb-2">
      <h5><%= @customer.last_name + @customer.first_name %>さんの会員詳細</h5>
    </div>
  </div>
  
  <!--テーブルメソッドを使用して一覧の表示-->
  <div class="row">
    <table class="table table-borderless pr-5" style="table-layout:fixed;">
      <tbody>
        <tr><th style="width:200px;">会員ID</th><td><%= @customer.id %></td></tr>
        <tr><th>氏名</th><td><%= @customer.last_name + " " + @customer.first_name %></td></tr>
        <tr><th>フリガナ</th><td><%= @customer.last_name_kana + " " + @customer.first_name_kana %></td></tr>
        <tr><th>郵便番号</th><td><%= @customer.postal_code %></td></tr>
        <tr><th>住所</th><td><%= @customer.address %></td></tr>
        <tr><th>電話番号</th><td><%= @customer.telephone_number %></td></tr>
        <tr><th>メールアドレス</th><td><%= @customer.email %></td></tr>
        <tr>
          <th>会員ステータス</th>
          <!--is_deleted初期値falseであれば有効、退会の場合trueになるので無効-->
          <td>
            <% if @customer.is_deleted == false %>
              <div class="text-success">有効</div>
            <% else %>
              <div class="text-danger">無効</div></div>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    
    <!--link_toのボタン-->
    <div class="mx-auto">
      <%= link_to "編集する", edit_admin_customer_path(params[:id]), class: "btn btn-success mr-5" %>
      <%= link_to "注文履歴一覧を見る", admin_root_path(customer_id: @customer.id), class: "btn btn-primary" %>
    </div>
  </div>
  
  
</div>