config/routes.rb
Rails.application.routes.draw do
  # adminとcustomerのdeviseを作成,アクションがかぶるので下記設定で整えた
  devise_for :admin, :skip => [:registrations, :password],
                      controllers: {sessions: 'admin/sessions'}
  
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  
  # namespaceを使用、pubilcのURLにはpublicを表示したくないので、scope modul:で実装
  scope modul: :public do
    root to: "public/homes#top"
    get "/about" => "public/homes#about"
    get "/customers/my_page" => "public/customers#show", as: "my_page"
    # get "/items" => "public/items#index"
    resources :items, only: [ :index,:show ], module: :public
    resources :addresses, only: [ :index, :create, :edit, :update, :destroy ], module: :public
    
    resources :customers, only: [ :edit, :update ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        get "unsubscribe"
        patch "withdraw"
      end 
    end 
    
    resources :orders, only: [ :new, :create, :index, :show ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        post "confirm"
        get "complete"
      end 
    end 
    
    resources :cart_items, only: [ :index, :update, :create, :destroy ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        delete "destroy_all"
      end 
    end 
  end 
  
  # namespaceを使用、adminのURLにはadminを表示するので、namespaceで実装
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [ :index, :new, :create, :show, :edit, :update ]
    resources :customers, only: [ :index, :show, :edit, :update ]
    resources :orders, only: [ :show, :update ]
    resources :genres, only: [ :index, :create, :edit, :update ]
    resources :order_details, only: [:update]
  end 
end

app/models/order.rb
class Order < ApplicationRecord
    
  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "制作中": 2, "発送準備中": 3, "発送済み": 4 }
  
  belongs_to:customer
  has_many:order_details, dependent: :destroy
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  def show
    @order = Order.find(params[:id])
    # OrderモデルとOrderDetailsはhas_manyとbelongs_toの関係
    @order_details = @order.order_details
  end 
  
  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to admin_order_path(params[:id])
  end 
  
  private
  
  # updateアクションでstatusの変更を受け付けるために実装
  def order_params
    params.require(:order).permit(:status)
  end 
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/show.html.erb
<div class="container-lg">
  <div class="row">
    <div class="col-2 bg-light text-center mb-2 ">
      <h5>注文履歴詳細</h5>
    </div>
  </div>
  
  <!--購入者の表示-->
  <div class="row mb-2">
    <div class="col-2">
      購入者
    </div>
    <div class="col-10">
      <%= link_to @order.customer.last_name + " " + @order.customer.first_name, admin_customer_path(@order.customer.id), class: "text-dark border-bottom border-dark" %>
    </div>
  </div>
  
  <!--注文日の表示-->
  <div class="row mb-2">
    <div class="col-2">
      注文日
    </div>
    <div class="col-10">
      <%= @order.created_at.strftime("%Y/%m/%d") %>
    </div>
  </div>
  
  <!--配達先の表示-->
  <div class="row mb-2">
    <div class="col-2">
      配送先
    </div>
    <div class="col-10">
      <%= @order.address %></br>
      <%= @order.name %>
    </div>
  </div>
  
  <!--支払い方法の表示-->
  <div class="row mb-2">
    <div class="col-2">
      支払方法
    </div>
    <div class="col-10">
      <%= @order.payment_method %>
    </div>
  </div>
  
  <!--注文ステータスの表示・更新-->
  <div class="row mb-2">
    <div class="col-2">
      注文ステータス
    </div>
    <div class="col-10">
      <!--orderscontrollerはadminにネストしているのでforom_withでパスの指示が必要-->
      <!--f.selectでenumに設定した項目をformで表示している-->
      <!--f.select :カラム名, モデル.カラム（複数形）.keys -->
      <%= form_with model:[:admin,@order], local:true do |f| %>
        <div class="form-group">
          <%= f.select :status, Order.statuses.keys %>
          <%= f.submit "更新", class: "btn btn-success ml-3" %>
        </div>
      <% end %>
    </div>
  </div>
  
  <!--注文商品テーブル・商品合計・送料・請求合計-->
  <div class="row mb-2">
    <div class="col-9">
      <table class="table">
        <thead class="bg-light">
            <tr>
                <th>商品名</th>
                <th>単価（税込）</th>
                <th>数量</th>
                <th>小計</th>
                <th>制作ステータス</th>
            </tr>
        </thead>
        <tbody>
            <!--Orderに含まれるorderdetailの数だけ表示-->
            <% @order_details.each do |od| %>
            <tr>
                <td>
                    <%= od.item.name %>
                </td> 
                <td><%= (od.price).to_s(:delimited) %></td>
                <td><%= (od.amount).to_s(:delimited) %></td>
                <td><%= (od.price * od.amount).to_s(:delimited) %></td>
                <td>
                  <%= form_with model:[:admin,od], local:true do |f| %>
                    <div class="form-group">
                      <%= f.select :making_status, OrderDetail.making_statuses.keys %>
                      <%= f.submit "更新", class: "btn btn-success ml-3" %>
                    </div>
                  <% end %>
                </td>
            </tr>
            <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-3">
      <table class="table table-borderless">
        <!--横向きテーブルの作成-->
        <thead>
            <tr><th>商品合計</th><td><%= (@order.total_payment - @order.shipping_cost).to_s(:delimited) %>円</td></tr>
            <tr><th>送料</th><td><%= (@order.shipping_cost).to_s(:delimited) %>円</td></tr>
            <tr><th>請求金額合計</th><td><%= (@order.total_payment).to_s(:delimited) %>円</td></tr>
        </thead>
    </div>
  </div>
  
  
</div>