config/routes.rb
Rails.application.routes.draw do
  # adminとcustomerのdeviseを作成,アクションがかぶるので下記設定で整えた
  devise_for :admin, :skip => [:registrations, :password],
                      controllers: {sessions: 'admin/sessions'}
  
  devise_for :customers, controllers: {
    sessions: 'customers/sessions',
    passwords: 'customers/passwords',
    registrations: 'customers/registrations'
  }
  
  # namespaceを使用、pubilcのURLにはpublicを表示したくないので、scope modul:で実装
  scope modul: :public do
    root to: "public/homes#top"
    get "/about" => "public/homes#about"
    get "/customers/my_page" => "public/customers#show", as: "my_page"
    # get "/items" => "public/items#index"
    resources :items, only: [ :index,:show ], module: :public
    resources :addresses, only: [ :index, :create, :edit, :update, :destroy ], module: :public
    
    resources :customers, only: [ :edit, :update ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        get "unsubscribe"
        patch "withdraw"
      end 
    end 
    
    resources :orders, only: [ :new, :create, :index, :show ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        post "confirm"
        get "complete"
      end 
    end 
    
    resources :cart_items, only: [ :index, :update, :create, :destroy ], module: :public do
      # resourcesを使用したコントローラーにルートを追加する方法の１つ、collectionを使用
      collection do
        delete "destroy_all"
      end 
    end 
  end 
  
  # namespaceを使用、adminのURLにはadminを表示するので、namespaceで実装
  namespace :admin do
    root to: "homes#top"
    resources :items, only: [ :index, :new, :create, :show, :edit, :update ]
    resources :customers, only: [ :index, :show, :edit, :update ]
    resources :orders, only: [ :show, :update ]
    resources :genres, only: [ :index, :create, :edit, :update ]
    resources :order_details, only: [:update]
  end 
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to:customer
  
  # public/orders/new.htmlでカラムをつなげた表示をするためにmodelで定義する
  def use_address
    "〒" + self.postal_code + self.address + self.name
  end 
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to:customer
  belongs_to:item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many:cart_items, dependent: :destroy
  has_many:orders, dependent: :destroy
  has_many:addresses, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  has_many:cart_items, dependent: :destroy
  has_many:order_details, dependent: :destroy
  belongs_to:genre
  
  # refileやattachment imgを使用するために必要
  attachment :image
end

app/models/order.rb
class Order < ApplicationRecord
    
  enum payment_method: { "クレジットカード": 0, "銀行振込": 1 }
  enum status: { "入金待ち": 0, "入金確認": 1, "制作中": 2, "発送準備中": 3, "発送済み": 4 }
  
  belongs_to:customer
  has_many:order_details, dependent: :destroy
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  enum making_status: { "制作不可": 0, "制作待ち": 1, "製作中": 2, "制作完了": 3 }
  
  belongs_to:order 
  belongs_to:item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genres = Genre.all
  end 
  
  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end 
  
  def edit
    @genre = Genre.find(params[:id])
  end 
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(edit_genre_params)
    redirect_to admin_genres_path
  end 
  
  
  private

  # require.(:genre)をつけるとエラーが出た。genreが空？
  # 下記のように削除するとひとまず実装できた。
  def genre_params
    params.permit(:name)
  end
  
  def edit_genre_params
    params.require(:genre).permit(:name)
  end

  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    
    # 遷移元の内容を取得
    path = Rails.application.routes.recognize_path(request.referer)
    
    # ヘッダーからアクセスした場合
    if params[:is_from_header] == "1"
      @orders = Order.page(params[:page]).reverse_order
      
    # それ以外（カスタマー詳細画面から遷移や戻る操作）
    else
      # カスタマー詳細画面からの遷移を分岐、pathのコントローラーとアクションで認識
      if path[:controller] == "admin/customers" && path[:action] == "show"
        @customer = Customer.find(params[:customer_id])
        @orders = @customer.orders.page(params[:page]).reverse_order
      
      # 戻る操作などによるエラー対策
      else
        @orders = Order.page(params[:page]).reverse_order
      end 
    end 
  end 
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @items = Item.page(params[:page])
  end 
  
  def new 
    @item = Item.new
  end 
  
  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end 
  
  def show
    @item = Item.find(params[:id])
  end 
  
  def edit
    @item = Item.find(params[:id])
  end 
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end 
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id,:name,:image,:introduction,
                                 :price,:is_active)
  end 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # deviseの導入により、初期値以外のデータ操作の許可、今回の場合は登録時
  # devise利用の機能が使われる場合にその前にconfigure_permitted_parametersが実行される
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  # adminがログアウトしたときのルート変更
  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :admin
      new_admin_session_path
    else
      root_path
    end 
  end 
  
  
  protected
  # ユーザー登録の際に,性、名などのデータ操作が許可される
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,
                                                       :first_name_kana,:postal_code,:address,
                                                       :telephone_number,:is_deleted])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/1d4b351902.js" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <!--Bootstrapのcontainer指定-->
        <div class="container">
          <!--pはpadding,上下左右に適用-->
          <a class="navbar-brand p-3" href="/">LOGO</a>
          <!--ハンバーガーアイコン部分、spanは三本線-->
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <!--開く前に隠す部分collapse,idは任意で、上記のdata-taegetに#[id]は必須-->
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <!--ユーザーのサインイン・アウトによる分岐-->
              <% if customer_signed_in? %>
                <!--do endを用いてfontawesomeアイコンと文字を表示する方法-->
                <li class="nav-item mr-4">
                  ようこそ、<%= current_customer.last_name %>さん！
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", my_page_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "カート", cart_items_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-secondary mr-5 nav-link" %>
                </li>
              <% elsif admin_signed_in? %>
                <li class="nav-item">
                  <%= link_to "商品一覧", admin_items_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "会員一覧", admin_customers_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "注文履歴一覧", admin_root_path(is_from_header: 1), class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-secondary mr-5 nav-link" %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "about", about_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_customer_session_path, class: 'btn btn-outline-secondary mr-5 nav-link' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
    <main>
      <%= yield %>
    </main>
    
    <footer>
      <div class="container mt-5">
      </div>
    </footer>
    
  </body>
</html>